name: Docker Build and Push

on:
  push:
    branches-ignore:
      - main  # Change this to your main branch"

jobs:
  build:
    runs-on: [self-hosted, win10]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          context: .
          push: true
          tags: navmlk/plchallenge:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yml
